apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: event-manager-app
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: event-manager-frontend:1.0.0
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"