apiVersion: v1
kind: ConfigMap
metadata:
  name: event-manager-config
  namespace: event-manager-app
data:
  DB_HOST: "postgres-statefulset-0.postgres-headless"
  DB_PORT: "5432"
  DB_NAME: "event_db"
  QUEUE_HOST: "rabbitmq-statefulset-0.rabbitmq-headless"
  QUEUE_PORT: "5672"