apiVersion: v1
kind: Secret
metadata:
  name: event-manager-secret
  namespace: event-manager-app
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: YWRtaW4=
  QUEUE_USER: YWRtaW4=
  QUEUE_PASSWORD: YWRtaW4=