apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: event-manager-app
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: event-manager-worker:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-manager-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: event-manager-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: event-manager-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: event-manager-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-manager-secret
                  key: DB_PASSWORD
            - name: QUEUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-manager-config
                  key: QUEUE_HOST
            - name: QUEUE_PORT
              valueFrom:
                configMapKeyRef:
                  name: event-manager-config
                  key: QUEUE_PORT
            - name: QUEUE_USER
              valueFrom:
                secretKeyRef:
                  name: event-manager-secret
                  key: QUEUE_USER
            - name: QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-manager-secret
                  key: QUEUE_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"