apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: event-manager-app
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080